#!/bin/bash

echo "Running blackbox test: boundary_test.py"
python -m pytest blackbox_test/boundary/boundary_test.py -v
echo

echo "Running blackbox test: ecp_test.py"
python -m pytest blackbox_test/ecp/ecp_test.py -v
echo

echo "Running blackbox test: fuzzing_test.py"
python -m pytest blackbox_test/fuzzing/fuzzing_test.py -v
echo

echo "Running blackbox test: state_machine_test.py"
python -m pytest blackbox_test/state_machine/state_machine_test.py -v
echo

echo "Running whitebox test: coverage_test.py"
python -m pytest whitebox_test/statement_coverage_and_branch_coverage/coverage_test.py -v
echo

echo "Running whitebox test: all_def_test.py"
python -m pytest whitebox_test/all_defs/all_defs_test.py -v
echo

echo "All tests finished."

echo "Cleaning up the redundant files generated by tests"
python tools/clean_redundant_files.py
echo

# Wait for user input (only relevant if running interactively)
read -p "Press Enter to exit..."
